import { Inter } from "next/font/google";
import "./globals.css";

// import Navbar from "../components/Navbar";
import TransitinProvider from "../components/TransitionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aman's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitinProvider>{children} </TransitinProvider>
      </body>
    </html>
  );
}
